server:
  image: rancher/k3s:v0.8.0
  command: server --disable-agent --no-deploy traefik --log /output/k3s.log
  environment:
    - K3S_CLUSTER_SECRET=somethingtotallyrandom
    - K3S_KUBECONFIG_OUTPUT=/output/kubeconfig.yaml
    - K3S_KUBECONFIG_MODE=666
  volumes:
    - ./in:/output
    - ./in:/var/lib/rancher/k3s/server/manifests
  ports:
    - 6443:6443

node:
  image: rancher/k3s:v0.8.0
  privileged: true
  links:
    - server
  environment:
    - K3S_URL=https://server:6443
    - K3S_CLUSTER_SECRET=somethingtotallyrandom
  volumes:
    # allow to use local images
    - ./images:/var/lib/rancher/k3s/agent/images
  ports:
    - 80:80
    - 443:443
    - 8080:8080
    - 27017:27017
