apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-dynamic-configmap
  namespace: default
data:
  dynamic.toml: |
    [[http.services.wrr1.weighted.services]]
      name = "default-mirror1@kubernetescrd"
    # uses a custom k8s namespace
    [[http.services.wrr2.weighted.services]]
      name = "toto-mirror2@kubernetescrd"

