apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: test.route
  namespace: default

spec:
  entryPoints:
    - web

  routes:
  - match: Host(`server`) && PathPrefix(`/bar`)
    kind: Rule
    services:
    - name: whoami@kubernetescrd
      port: 80


